# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ae4d30d6cef1ff4e52b2f02ad89481ea8eef23894330548b3e422b7d2c115c88a896856f80ee02efc3f13e1c07ebe0887c1a016079bc47fd782ccbada480bb1

test:
  secret_key_base: 0b8d8e437c6229805f70ea2a77ef3b27f5e1eef6fb682c764d399cd081e18e070573398c0c4fbd610f9657b6a237307abfc13999b5b48175e37e1328b347f1ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
